"""init

Revision ID: 70cadcb9dfd5
Revises:
Create Date: 2023-02-16 16:29:37.419295

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "70cadcb9dfd5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person_citizen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("person_name", sa.String(), nullable=False),
        sa.Column("person_email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_person_citizen_id"), "person_citizen", ["id"], unique=False
    )
    op.create_table(
        "person_officer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("officer_name", sa.String(length=255), nullable=False),
        sa.Column("identification", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identification"),
    )
    op.create_index(
        op.f("ix_person_officer_id"), "person_officer", ["id"], unique=False
    )
    op.create_table(
        "infractions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("patent", sa.String(length=25), nullable=False),
        sa.Column("brand", sa.String(length=255), nullable=True),
        sa.Column("color", sa.String(length=255), nullable=True),
        sa.Column("reason_infraction", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "vehicule_type",
            sa.Enum("car", "moto", "big_card", name="typevehiculechoice"),
            nullable=False,
        ),
        sa.Column("person_citizen_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_citizen_id"],
            ["person_citizen.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("patent"),
    )
    op.create_index(op.f("ix_infractions_id"), "infractions", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_infractions_id"), table_name="infractions")
    op.drop_table("infractions")
    op.drop_index(op.f("ix_person_officer_id"), table_name="person_officer")
    op.drop_table("person_officer")
    op.drop_index(op.f("ix_person_citizen_id"), table_name="person_citizen")
    op.drop_table("person_citizen")
    # ### end Alembic commands ###
